### ISSUE TITLE
SFH487-2 alternative

### ISSUE THREAD

**Issue by Jumbo125** [Ixtalo/MyVitotronicLogger#1]
Hello

I  want to build a optolink adapter with my wemos D1

I can't pay a SFH487-2. Is there a alternative???

Thank you for your help

**Comment by Jumbo125** [comment]
hello 
i found a alternative. thank you to arduino-forum1

can you tell me, why you wiring D8 to the RX?

**Comment by Ixtalo** [comment]
> hello i found a alternative. thank you to arduino-forum1
> 
> can you tell me, why you wiring D8 to the RX?

As quoted in the `README.md`: I'm following the wiring from https://github.com/openv/openv/wiki/Bauanleitung-ESP8266.
